### ISSUE TITLE
Parsed JSON object/hash requires a target configuration option?

### ISSUE THREAD

**Issue by richzw** [logstash-plugins/logstash-filter-json#44]
- Version: logstash - 7.3.0
- Operating System: centos - docker 
- Config File :
```
    filter {
      json{
        source => "message"
        skip_on_invalid_json => true
        remove_field => [ "message" ]
      }
    }
```

- Sample Data:
json - Parsed JSON object/hash requires a target configuration option {:source=>"message", :raw=>"[{\"slot\":\"login\",\"elapsedTime\":6.964,\"result\":0,\"interval\":17}]"}

Could someone figure out the reason of this warning?

**Comment by ppreyas** [comment]
Hi Richzw,
Have you tried adding a target setting?

Try something like the below:

filter {
      json{
        source => "message"
        target => "value"
        skip_on_invalid_json => true
        remove_field => [ "message" ]
      }
    }

**Comment by kares** [comment]
*target* is simply required in this case for the filter to decide where to put the parsed (JSON) structure
for your case its an array `[...]` so the plugin can not decide where to put it - simply does nothing.

since you intend to remove the *"message"* field try putting (overwriting) it there e.g. : 
`filter { json { source => "message" skip_on_invalid_json => true target => "message" } }`

for your input: `[{"slot":"login","elapsedTime":6.964,"result":0,"interval":17}]` 
you will than get the parsed array structure under the **message** field like so : 
```ruby
{
   "message" => [
        [0] {
                 "result" => 0,
               "interval" => 17,
                   "slot" => "login",
            "elapsedTime" => 6.964
        }
    ],
}
```
